export const business: string;
export const pricingBoxItem: string;
export const pricingHeading: string;
export const pricingTerms: string;
export const pricingContainer: string;
export const pricingAction: string;
export const container: string;
export const titleText: string;
export const descText: string;
